import DailyContributionWebScrapperCheerioAdapter from "../streak/DailyContributionWebScrapperCheerioAdapter"
import CreateGithubProfileDailyContributionList from "../utils/CreateGithubProfileDailyContributionList";

new CreateGithubProfileDailyContributionList(new DailyContributionWebScrapperCheerioAdapter());